// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: common/base_response.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StatusCode      int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	IsSuccess       bool                   `protobuf:"varint,2,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ValidationError []*ValidationError     `protobuf:"bytes,4,rep,name=validation_error,json=validationError,proto3" json:"validation_error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_common_base_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_base_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_common_base_response_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BaseResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseResponse) GetValidationError() []*ValidationError {
	if x != nil {
		return x.ValidationError
	}
	return nil
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_common_base_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_common_base_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_common_base_response_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_base_response_proto protoreflect.FileDescriptor

const file_common_base_response_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/base_response.proto\x12\x06common\"\xac\x01\n" +
	"\fBaseResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"is_success\x18\x02 \x01(\bR\tisSuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12B\n" +
	"\x10validation_error\x18\x04 \x03(\v2\x17.common.ValidationErrorR\x0fvalidationError\"A\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB Z\x1egrpc-course-protobuf/pb/commonb\x06proto3"

var (
	file_common_base_response_proto_rawDescOnce sync.Once
	file_common_base_response_proto_rawDescData []byte
)

func file_common_base_response_proto_rawDescGZIP() []byte {
	file_common_base_response_proto_rawDescOnce.Do(func() {
		file_common_base_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_base_response_proto_rawDesc), len(file_common_base_response_proto_rawDesc)))
	})
	return file_common_base_response_proto_rawDescData
}

var file_common_base_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_base_response_proto_goTypes = []any{
	(*BaseResponse)(nil),    // 0: common.BaseResponse
	(*ValidationError)(nil), // 1: common.ValidationError
}
var file_common_base_response_proto_depIdxs = []int32{
	1, // 0: common.BaseResponse.validation_error:type_name -> common.ValidationError
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_base_response_proto_init() }
func file_common_base_response_proto_init() {
	if File_common_base_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_base_response_proto_rawDesc), len(file_common_base_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_base_response_proto_goTypes,
		DependencyIndexes: file_common_base_response_proto_depIdxs,
		MessageInfos:      file_common_base_response_proto_msgTypes,
	}.Build()
	File_common_base_response_proto = out.File
	file_common_base_response_proto_goTypes = nil
	file_common_base_response_proto_depIdxs = nil
}
